id: P000669
initial_creation_type: ocr
source_metadata:
  id: bdr:W20043
  title: བདུད་རྩི་སྨན་གྱི་འཁྲུངས་དཔེ
  author: ''
  volumes:
    9157f00de5474d47a7683458ebc61111:
      image_group_id: I1PD36399
      title: ''
      volume_number: 1
      total_pages: 848
